server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka



logging:
  level:
    org:
      springframework:
        cloud:
          commons:
            util:
              InetUtils: trace